name: CES
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - ipykernel
  - jupyter
  - nbconvert
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - geopandas
  - proj
  - proj-data
  - pytest
  - shapely
